#include "lib/Domains/domain.hpp"
#include "lib/Entities/entity.hpp"
#include "controllers/cntrPresentation.hpp"
#include "controllers/cntrService.hpp"
#include "lib/Curses/curses.h"
#include "interfaces.hpp"